plugins {
    id 'java-library'
}

dependencies {
    compileOnly 'org.slf4j:slf4j-api:1.7.36'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.slf4j:slf4j-api:1.7.36'
    testRuntimeOnly 'ch.qos.logback:logback-classic:1.2.13'
}

test {
    useJUnitPlatform()
}
